apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple_web_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs_app
  template:
    metadata:
      labels:
        app: nodejs_app
    spec:
      containers:
      - name: simple_web_app
        image: partha00011/simple_web_app
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: simple_web_app_svc
spec:
  type: NodePort
  selector:
    app: nodejs_app
  ports:
  - port: 8080
    targetPort: 80
