apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: simple-webapp-container
        image: partha00011/simple_web_app
        imagePullPolicy: Always
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-svc
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
  - port: 8080
    targetPort: 8080
